[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "plogic"
version = "2.2.0"
description = "Programmable Photonic Logic: control, simulation, and characterization"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT License"}
authors = [{name = "Open Photonics Lab"}]
dependencies = [
  "numpy",
  "pandas",
  "scipy",
  "matplotlib"
]

[project.scripts]
plogic = "plogic.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
